<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<?php $isEdit = ! empty($equipment); ?>
<?php if (session('success')): ?><div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-emerald-800"><?= esc(session('success')) ?></div><?php endif ?>
<?php if (session('error')): ?><div class="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-red-800"><?= esc(session('error')) ?></div><?php endif ?>
<div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><a href="<?= route_to('equipment.index') ?>" class="text-sm font-semibold text-cyan-700">← Volver al catálogo</a><p class="mt-4 text-xs font-bold uppercase tracking-[.2em] text-cyan-600">Resource Engine · 9.1</p><h2 class="mt-2 text-3xl font-bold text-slate-950"><?= $isEdit ? esc($equipment['code']) : 'Registrar maquinaria/equipo' ?></h2><p class="mt-2 text-sm text-slate-600">Configura el recurso físico y los perfiles humanos que necesita para operar.</p></div></div>
<form method="post" action="<?= $isEdit ? route_to('equipment.update', $equipment['id']) : route_to('equipment.store') ?>" class="space-y-6">
<?= csrf_field() ?>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="mb-5"><p class="text-xs font-bold uppercase tracking-[.18em] text-cyan-600">Identidad del recurso</p><h3 class="mt-1 text-xl font-bold">Datos generales</h3></div><div class="grid gap-5 md:grid-cols-2 xl:grid-cols-3">
<label><span class="mb-2 block text-sm font-semibold">Código *</span><input required name="code" value="<?= esc(old('code', $equipment['code'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="GRU-080-01"></label>
<label><span class="mb-2 block text-sm font-semibold">Nombre *</span><input required name="name" value="<?= esc(old('name', $equipment['name'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3" placeholder="Grúa telescópica 80 ton"></label>
<label><span class="mb-2 block text-sm font-semibold">Categoría</span><select name="category_id"><option value="">Sin categoría</option><?php foreach ($categories as $category): ?><option value="<?= esc((string)$category['id']) ?>" <?= (string)old('category_id', $equipment['category_id'] ?? '') === (string)$category['id'] ? 'selected' : '' ?>><?= esc($category['code']) ?> — <?= esc($category['name']) ?></option><?php endforeach ?></select></label>
<label><span class="mb-2 block text-sm font-semibold">Marca</span><input name="brand" value="<?= esc(old('brand', $equipment['brand'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3"></label>
<label><span class="mb-2 block text-sm font-semibold">Modelo</span><input name="model" value="<?= esc(old('model', $equipment['model'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3"></label>
<label><span class="mb-2 block text-sm font-semibold">Año</span><input type="number" min="1950" max="2100" name="year" value="<?= esc(old('year', $equipment['year'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3"></label>
<label><span class="mb-2 block text-sm font-semibold">Serie</span><input name="serial_number" value="<?= esc(old('serial_number', $equipment['serial_number'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3"></label>
<label><span class="mb-2 block text-sm font-semibold">Placa</span><input name="plate_number" value="<?= esc(old('plate_number', $equipment['plate_number'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3"></label>
</div></section>
<section class="grid gap-6 lg:grid-cols-2"><article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.18em] text-cyan-600">Disponibilidad</p><div class="mt-5 space-y-4"><label><span class="mb-2 block text-sm font-semibold">Estado operativo</span><select name="operational_status"><option value="available">Disponible</option><option value="reserved">Reservado</option><option value="assigned">Asignado</option><option value="in_operation">En operación</option><option value="returning">Retornando</option><option value="out_of_service">Fuera de servicio</option></select></label><label><span class="mb-2 block text-sm font-semibold">Estado de mantenimiento</span><select name="maintenance_status"><option value="ok">Mantenimiento al día</option><option value="preventive_due">Preventivo próximo</option><option value="preventive">En preventivo</option><option value="corrective">En correctivo</option><option value="out_of_service">Fuera de servicio</option></select></label></div></article><article class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-bold uppercase tracking-[.18em] text-amber-600">Preparado para mantenimiento</p><div class="mt-5 grid gap-4 sm:grid-cols-2"><label><span class="mb-2 block text-sm font-semibold">Tipo de medidor</span><select name="meter_type"><option value="">No aplica</option><option value="hours">Horas</option><option value="kilometers">Kilómetros</option><option value="cycles">Ciclos</option></select></label><label><span class="mb-2 block text-sm font-semibold">Lectura actual</span><input type="number" min="0" step="0.01" name="current_meter" value="<?= esc(old('current_meter', $equipment['current_meter'] ?? '')) ?>" class="w-full rounded-xl border border-slate-300 px-4 py-3"></label></div><p class="mt-4 text-xs leading-5 text-slate-500">Estos datos permitirán más adelante bloquear asignaciones por mantenimiento preventivo/correctivo.</p></article></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><p class="text-xs font-bold uppercase tracking-[.18em] text-violet-600">Configuración operativa</p><h3 class="mt-1 text-xl font-bold">Personal requerido para operar</h3><p class="mt-2 text-sm text-slate-600">Selecciona únicamente los roles aplicables. Los obligatorios bloquearán la futura generación de OT si no están cubiertos.</p></div><div class="mt-6 space-y-3"><?php foreach ($roles as $role): ?><?php $req = $requirements[(int)$role['id']] ?? null; ?><div class="grid gap-3 rounded-xl border border-slate-200 p-4 md:grid-cols-[auto_minmax(0,1fr)_180px_120px_120px]"><label class="flex items-center"><input type="checkbox" name="role_id[]" value="<?= esc((string)$role['id']) ?>" <?= $req ? 'checked' : '' ?>></label><div><p class="font-semibold text-slate-950"><?= esc($role['name']) ?></p><p class="text-xs text-slate-500"><?= esc($role['description'] ?? '') ?></p></div><select name="requirement_type[<?= esc((string)$role['id']) ?>]"><option value="required" <?= ($req['requirement_type'] ?? '') === 'required' ? 'selected' : '' ?>>Obligatorio</option><option value="optional" <?= ($req['requirement_type'] ?? 'optional') === 'optional' ? 'selected' : '' ?>>Opcional</option></select><input type="number" min="0" name="min_quantity[<?= esc((string)$role['id']) ?>]" value="<?= esc((string)($req['min_quantity'] ?? 1)) ?>" class="rounded-xl border border-slate-300 px-3 py-2" title="Cantidad mínima"><input type="number" min="0" name="max_quantity[<?= esc((string)$role['id']) ?>]" value="<?= esc((string)($req['max_quantity'] ?? 1)) ?>" class="rounded-xl border border-slate-300 px-3 py-2" title="Cantidad máxima"><input type="hidden" name="role_notes[<?= esc((string)$role['id']) ?>]" value=""></div><?php endforeach ?></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><label><span class="mb-2 block text-sm font-semibold">Observaciones</span><textarea name="notes" rows="4" class="w-full rounded-xl border border-slate-300 px-4 py-3"><?= esc(old('notes', $equipment['notes'] ?? '')) ?></textarea></label></section>
<div class="flex justify-end"><button class="rounded-xl bg-slate-950 px-6 py-3 font-bold text-white">Guardar configuración</button></div>
</form>
<script>document.addEventListener('DOMContentLoaded',()=>{const setValue=(name,value)=>{const el=document.querySelector(`[name="${name}"]`);if(!el)return;const inst=window.traceOpxChoices?.get(el);if(inst)inst.setChoiceByValue(String(value||''));else el.value=value||'';};setValue('operational_status','<?= esc(old('operational_status', $equipment['operational_status'] ?? 'available')) ?>');setValue('maintenance_status','<?= esc(old('maintenance_status', $equipment['maintenance_status'] ?? 'ok')) ?>');setValue('meter_type','<?= esc(old('meter_type', $equipment['meter_type'] ?? '')) ?>');});</script>
<?= $this->endSection() ?>
