<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<?php $docLabel=$documentTypes[$billingCase['document_type']] ?? $billingCase['document_type']; ?>
<?php if(session('success')): ?><div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-800"><?= esc(session('success')) ?></div><?php endif ?>
<div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-cyan-600">Billing Workspace</p><h2 class="mt-2 text-3xl font-bold text-slate-950"><?= esc($billingCase['code']) ?></h2><div class="mt-3 flex flex-wrap gap-3"><a href="<?= route_to('service_cases.show',$billingCase['service_case_id']) ?>" class="font-bold text-violet-700"><?= esc($billingCase['service_case_code']) ?> ↗</a><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Borrador fiscal</span></div></div><a href="<?= route_to('billing.index') ?>" class="rounded-xl border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-700">Volver a facturación</a></div>

<section class="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase tracking-wide text-slate-500">Cliente</p><p class="mt-3 text-lg font-bold"><?= esc($billingCase['business_name']) ?></p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase tracking-wide text-slate-500">Documento objetivo</p><p class="mt-3 text-lg font-bold"><?= esc($docLabel) ?></p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase tracking-wide text-slate-500">Total acordado</p><p class="mt-3 text-lg font-bold">$<?= number_format((float)$billingCase['invoiceable_amount'],2) ?></p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase tracking-wide text-slate-500">Saldo financiero</p><p class="mt-3 text-lg font-bold">$<?= number_format((float)$billingCase['balance_amount'],2) ?></p></article></section>

<div class="mt-6 grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]"><div class="space-y-6">
<section class="rounded-2xl border border-cyan-200 bg-cyan-50/40 p-6"><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-700">Origen trazable</p><h3 class="mt-2 text-xl font-bold">Del cierre operativo a facturación</h3><div class="mt-5 grid gap-3 md:grid-cols-3"><div class="rounded-xl bg-white p-4"><p class="text-xs text-slate-500">Cotización</p><p class="mt-2 font-bold"><?= esc($billingCase['quotation_code']) ?></p></div><div class="rounded-xl bg-white p-4"><p class="text-xs text-slate-500">Orden de Trabajo</p><p class="mt-2 font-bold"><?= esc($billingCase['work_order_code']) ?></p></div><div class="rounded-xl bg-white p-4"><p class="text-xs text-slate-500">Condición comercial</p><p class="mt-2 font-bold"><?= esc($billingCase['payment_term_name_snapshot'] ?: 'Sin condición') ?></p></div></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-[.18em] text-violet-600">Plan financiero heredado</p><h3 class="mt-2 text-xl font-bold">Calendario esperado de cobro</h3><p class="mt-2 text-sm text-slate-500">Este plan nace de la condición de pago de la cotización. Los pagos reales se registrarán posteriormente con evidencia bancaria.</p><div class="mt-5 space-y-3"><?php foreach($schedule as $item): ?><article class="flex flex-col gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-bold"><?= esc($item['concept']) ?></p><p class="mt-1 text-xs text-slate-500"><?= number_format((float)$item['percentage'],2) ?>% · <?= esc(str_replace('_',' ',$item['trigger_event'] ?? '')) ?></p></div><div class="text-right"><p class="text-lg font-bold">$<?= number_format((float)$item['amount'],2) ?></p><span class="text-xs font-semibold text-amber-700">Pendiente</span></div></article><?php endforeach ?></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Notas</p><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-700"><?= esc($billingCase['notes'] ?: 'Sin notas adicionales.') ?></p></section>
</div><aside class="space-y-6 xl:sticky xl:top-6 xl:self-start"><section class="rounded-2xl bg-slate-950 p-6 text-white shadow-xl"><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-400">Próxima acción</p><h3 class="mt-3 text-xl font-bold">Revisar datos fiscales</h3><p class="mt-3 text-sm leading-6 text-slate-300">El siguiente incremento validará identificación fiscal, dirección, documento objetivo y convertirá esta preparación en un documento listo para emisión electrónica.</p></section><section class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Estado financiero</p><dl class="mt-5 space-y-4 text-sm"><div class="flex justify-between"><dt class="text-slate-500">Facturable</dt><dd class="font-bold">$<?= number_format((float)$billingCase['invoiceable_amount'],2) ?></dd></div><div class="flex justify-between"><dt class="text-slate-500">Pagado</dt><dd class="font-bold">$<?= number_format((float)$billingCase['paid_amount'],2) ?></dd></div><div class="flex justify-between"><dt class="text-slate-500">Pendiente</dt><dd class="font-bold">$<?= number_format((float)$billingCase['balance_amount'],2) ?></dd></div></dl></section></aside></div>
<?= $this->endSection() ?>
