<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>

<?php if (session('success')): ?>
<div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-800"><?= esc(session('success')) ?></div>
<?php endif ?>
<?php if (session('error')): ?>
<div class="mb-5 rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-rose-800"><?= esc(session('error')) ?></div>
<?php endif ?>

<div class="mb-7">
    <p class="text-xs font-semibold uppercase tracking-[.2em] text-cyan-600">DTE Engine</p>
    <h2 class="mt-2 text-3xl font-bold text-slate-950">Configuración de Facturación Electrónica</h2>
    <p class="mt-2 max-w-3xl text-sm leading-6 text-slate-600">Administra la infraestructura utilizada para construir el número de control, identificar sucursales y puntos de venta y mapear unidades comerciales al CAT-014 del Ministerio de Hacienda.</p>
</div>

<section class="grid gap-4 lg:grid-cols-3">
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-slate-500">Sucursales DTE</p><p class="mt-2 text-3xl font-bold"><?= count($establishments) ?></p><p class="mt-2 text-sm text-slate-500">Cada una utiliza un código MH de 4 caracteres.</p></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-slate-500">Puntos de venta</p><p class="mt-2 text-3xl font-bold"><?= count($pointsOfSale) ?></p><p class="mt-2 text-sm text-slate-500">Se encuentran vinculados a una sucursal.</p></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs uppercase tracking-wide text-slate-500">CAT-014 cargado</p><p class="mt-2 text-3xl font-bold"><?= count($mhUnits) ?></p><p class="mt-2 text-sm text-slate-500">Unidades oficiales disponibles para mapeo.</p></article>
</section>

<div class="mt-6 grid gap-6 xl:grid-cols-2">
    <section id="establishments" class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <?php $editingEst = $editEstablishment !== null; ?>
        <div class="flex items-start justify-between gap-4">
            <div><p class="text-xs font-semibold uppercase tracking-[.18em] text-violet-600">Numeración DTE</p><h3 class="mt-2 text-xl font-bold"><?= $editingEst ? 'Modificar sucursal' : 'Registrar sucursal' ?></h3></div>
            <?php if ($editingEst): ?><a href="<?= route_to('dte_settings.index') ?>#establishments" class="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-slate-700">Cancelar</a><?php endif ?>
        </div>
        <p class="mt-2 text-sm text-slate-500">El código MH participa directamente en el número de control. Una vez utilizado fiscalmente queda protegido.</p>
        <?php if ($editingEst && !empty($editEstablishment['mh_code_locked'])): ?><div class="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">El código MH ya fue utilizado en numeración fiscal y no puede modificarse. Los demás datos sí pueden actualizarse.</div><?php endif ?>
        <form method="post" action="<?= $editingEst ? route_to('dte_settings.establishments.update', (int)$editEstablishment['id']) : route_to('dte_settings.establishments.store') ?>" class="mt-5 grid gap-4 sm:grid-cols-2" data-processing-message="<?= $editingEst ? 'Actualizando sucursal DTE…' : 'Guardando sucursal DTE…' ?>">
            <?= csrf_field() ?>
            <label class="text-sm font-semibold text-slate-700">Código interno<input name="code" value="<?= esc(old('code', $editEstablishment['code'] ?? '')) ?>" required maxlength="20" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"></label>
            <label class="text-sm font-semibold text-slate-700">Código MH
                <?php if ($editingEst && !empty($editEstablishment['mh_code_locked'])): ?><input type="hidden" name="mh_code" value="<?= esc($editEstablishment['mh_code']) ?>"><input value="<?= esc($editEstablishment['mh_code']) ?>" disabled class="mt-2 w-full cursor-not-allowed rounded-xl border border-slate-200 bg-slate-100 px-4 py-3 font-mono font-normal text-slate-500"><?php else: ?><input name="mh_code" value="<?= esc(old('mh_code', $editEstablishment['mh_code'] ?? '')) ?>" required maxlength="4" placeholder="M001" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-mono font-normal uppercase"><?php endif ?>
            </label>
            <label class="sm:col-span-2 text-sm font-semibold text-slate-700">Nombre<input name="name" value="<?= esc(old('name', $editEstablishment['name'] ?? '')) ?>" required maxlength="120" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"></label>
            <label class="text-sm font-semibold text-slate-700">Referencia interna<input name="internal_code" value="<?= esc(old('internal_code', $editEstablishment['internal_code'] ?? '')) ?>" maxlength="10" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"></label>
            <label class="flex items-center gap-3 self-end rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-700"><input type="checkbox" name="is_default" value="1" class="h-4 w-4" <?= !empty($editEstablishment['is_default']) ? 'checked' : '' ?>> Sucursal predeterminada</label>
            <?php if ($editingEst): ?><label class="sm:col-span-2 text-sm font-semibold text-slate-700">Estado<select name="status" data-native="true" class="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal"><option value="1" <?= (int)$editEstablishment['status']===1?'selected':'' ?>>Activa</option><option value="0" <?= (int)$editEstablishment['status']===0?'selected':'' ?>>Inactiva</option></select></label><?php endif ?>
            <div class="sm:col-span-2"><button class="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white"><?= $editingEst ? 'Guardar cambios' : 'Guardar sucursal' ?></button></div>
        </form>
        <div class="mt-6 overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-500"><th class="py-3">Sucursal</th><th class="py-3">Código MH</th><th class="py-3">Estado</th><th class="py-3 text-right">Acción</th></tr></thead><tbody class="divide-y divide-slate-100"><?php foreach($establishments as $row): ?><tr><td class="py-3"><p class="font-semibold"><?= esc($row['name']) ?></p><p class="text-xs text-slate-500"><?= esc($row['code']) ?></p></td><td class="py-3 font-mono font-bold"><?= esc($row['mh_code']) ?></td><td class="py-3"><?= (int)$row['status'] === 1 ? 'Activa' : 'Inactiva' ?></td><td class="py-3 text-right"><a href="<?= route_to('dte_settings.index') ?>?edit_establishment=<?= (int)$row['id'] ?>#establishments" class="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">Editar</a></td></tr><?php endforeach ?></tbody></table></div>
    </section>

    <section id="points-of-sale" class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <?php $editingPos = $editPointOfSale !== null; ?>
        <div class="flex items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-violet-600">Numeración DTE</p><h3 class="mt-2 text-xl font-bold"><?= $editingPos ? 'Modificar punto de venta' : 'Registrar punto de venta' ?></h3></div><?php if($editingPos): ?><a href="<?= route_to('dte_settings.index') ?>#points-of-sale" class="rounded-xl border border-slate-300 bg-white px-4 py-2 text-sm font-bold text-slate-700">Cancelar</a><?php endif ?></div>
        <p class="mt-2 text-sm text-slate-500">El código MH del punto de venta se concatena con el código de sucursal.</p>
        <?php if ($editingPos && !empty($editPointOfSale['mh_code_locked'])): ?><div class="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">Este punto ya fue utilizado fiscalmente. Su sucursal y código MH quedan protegidos; nombre, referencias, estado y condición predeterminada sí pueden modificarse.</div><?php endif ?>
        <form method="post" action="<?= $editingPos ? route_to('dte_settings.points_of_sale.update', (int)$editPointOfSale['id']) : route_to('dte_settings.points_of_sale.store') ?>" class="mt-5 grid gap-4 sm:grid-cols-2" data-processing-message="<?= $editingPos ? 'Actualizando punto de venta DTE…' : 'Guardando punto de venta DTE…' ?>">
            <?= csrf_field() ?>
            <label class="sm:col-span-2 text-sm font-semibold text-slate-700">Sucursal
                <?php if($editingPos && !empty($editPointOfSale['mh_code_locked'])): ?><input type="hidden" name="establishment_id" value="<?= (int)$editPointOfSale['establishment_id'] ?>"><select disabled data-native="true" class="mt-2 w-full cursor-not-allowed rounded-xl border border-slate-200 bg-slate-100 px-4 py-3"><?php foreach($establishments as $row): ?><option <?= (int)$row['id']===(int)$editPointOfSale['establishment_id']?'selected':'' ?>><?= esc($row['name']) ?> · <?= esc($row['mh_code']) ?></option><?php endforeach ?></select><?php else: ?><select name="establishment_id" required class="mt-2 w-full" data-placeholder="Seleccionar sucursal"><option value="">Seleccionar</option><?php foreach($establishments as $row): ?><option value="<?= (int)$row['id'] ?>" <?= (int)old('establishment_id', $editPointOfSale['establishment_id'] ?? 0)===(int)$row['id']?'selected':'' ?>><?= esc($row['name']) ?> · <?= esc($row['mh_code']) ?></option><?php endforeach ?></select><?php endif ?>
            </label>
            <label class="text-sm font-semibold text-slate-700">Código interno<input name="code" value="<?= esc(old('code', $editPointOfSale['code'] ?? '')) ?>" required maxlength="20" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"></label>
            <label class="text-sm font-semibold text-slate-700">Código MH<?php if($editingPos && !empty($editPointOfSale['mh_code_locked'])): ?><input type="hidden" name="mh_code" value="<?= esc($editPointOfSale['mh_code']) ?>"><input value="<?= esc($editPointOfSale['mh_code']) ?>" disabled class="mt-2 w-full cursor-not-allowed rounded-xl border border-slate-200 bg-slate-100 px-4 py-3 font-mono font-normal text-slate-500"><?php else: ?><input name="mh_code" value="<?= esc(old('mh_code', $editPointOfSale['mh_code'] ?? '')) ?>" required maxlength="4" placeholder="P001" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-mono font-normal uppercase"><?php endif ?></label>
            <label class="sm:col-span-2 text-sm font-semibold text-slate-700">Nombre<input name="name" value="<?= esc(old('name', $editPointOfSale['name'] ?? '')) ?>" required maxlength="120" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"></label>
            <label class="text-sm font-semibold text-slate-700">Referencia interna<input name="internal_code" value="<?= esc(old('internal_code', $editPointOfSale['internal_code'] ?? '')) ?>" maxlength="15" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal"></label>
            <label class="flex items-center gap-3 self-end rounded-xl bg-slate-50 px-4 py-3 text-sm font-semibold text-slate-700"><input type="checkbox" name="is_default" value="1" class="h-4 w-4" <?= !empty($editPointOfSale['is_default']) ? 'checked' : '' ?>> Punto predeterminado</label>
            <?php if($editingPos): ?><label class="sm:col-span-2 text-sm font-semibold text-slate-700">Estado<select name="status" data-native="true" class="mt-2 w-full rounded-xl border border-slate-300 bg-white px-4 py-3 font-normal"><option value="1" <?= (int)$editPointOfSale['status']===1?'selected':'' ?>>Activo</option><option value="0" <?= (int)$editPointOfSale['status']===0?'selected':'' ?>>Inactivo</option></select></label><?php endif ?>
            <div class="sm:col-span-2"><button class="rounded-xl bg-slate-950 px-5 py-3 font-bold text-white"><?= $editingPos ? 'Guardar cambios' : 'Guardar punto de venta' ?></button></div>
        </form>
        <div class="mt-6 overflow-x-auto"><table class="w-full text-sm"><thead><tr class="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-500"><th class="py-3">Punto</th><th class="py-3">Alcance</th><th class="py-3 text-right">Acción</th></tr></thead><tbody class="divide-y divide-slate-100"><?php foreach($pointsOfSale as $row): ?><tr><td class="py-3"><p class="font-semibold"><?= esc($row['name']) ?></p><p class="font-mono text-xs text-slate-500"><?= esc($row['mh_code']) ?></p></td><td class="py-3"><span class="font-mono"><?= esc($row['establishment_mh_code']) . esc($row['mh_code']) ?></span><p class="text-xs text-slate-500"><?= esc($row['establishment_name']) ?></p></td><td class="py-3 text-right"><a href="<?= route_to('dte_settings.index') ?>?edit_point_of_sale=<?= (int)$row['id'] ?>#points-of-sale" class="rounded-lg border border-slate-300 bg-white px-3 py-2 text-xs font-bold text-slate-700">Editar</a></td></tr><?php endforeach ?></tbody></table></div>
    </section>
</div>

<section id="units" class="mt-6 rounded-2xl border border-slate-200 bg-white shadow-sm">
    <div class="border-b border-slate-200 p-6"><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-600">CAT-014</p><h3 class="mt-2 text-xl font-bold">Mapeo de unidades comerciales</h3><p class="mt-2 text-sm text-slate-500">La unidad comercial permanece intacta. Aquí se define qué código oficial de Hacienda debe copiarse al snapshot del DTE.</p></div>
    <div class="overflow-x-auto"><table class="w-full"><thead class="bg-slate-50"><tr><th class="px-5 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">Unidad comercial</th><th class="px-5 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">CAT-014 actual</th><th class="px-5 py-3 text-left text-xs font-bold uppercase tracking-wide text-slate-500">Asignar</th></tr></thead><tbody class="divide-y divide-slate-100"><?php foreach($commercialUnits as $unit): ?><tr><td class="px-5 py-4"><p class="font-semibold"><?= esc($unit['name']) ?></p><p class="text-xs text-slate-500"><?= esc($unit['code']) ?><?= $unit['symbol'] ? ' · '.esc($unit['symbol']) : '' ?></p></td><td class="px-5 py-4"><?php if($unit['mh_code']): ?><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">CAT-014 <?= str_pad((string)$unit['mh_code'],2,'0',STR_PAD_LEFT) ?> · <?= esc($unit['mh_name']) ?></span><?php else: ?><span class="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-800">Sin mapear</span><?php endif ?></td><td class="px-5 py-4"><form method="post" action="<?= route_to('dte_settings.units.map',(int)$unit['id']) ?>" class="flex min-w-[360px] items-center gap-2" data-processing-message="Actualizando mapeo CAT-014…"><?= csrf_field() ?><select name="mh_unit_measure_id" class="min-w-0 flex-1" data-placeholder="Seleccionar CAT-014"><option value="">Sin asignar</option><?php foreach($mhUnits as $mh): ?><option value="<?= (int)$mh['id'] ?>" <?= (int)($unit['mh_unit_measure_id']??0)===(int)$mh['id']?'selected':'' ?>><?= str_pad((string)$mh['code'],2,'0',STR_PAD_LEFT) ?> · <?= esc($mh['name']) ?></option><?php endforeach ?></select><button class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm font-bold text-slate-700">Guardar</button></form></td></tr><?php endforeach ?></tbody></table></div>
</section>

<section class="mt-6 rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
    <p class="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Correlativos</p>
    <h3 class="mt-2 text-xl font-bold">Secuencias anuales utilizadas</h3>
    <p class="mt-2 text-sm text-slate-500">Las filas aparecerán cuando un DTE reserve su primer número de control. Cada secuencia es independiente por año, tipo de documento, sucursal y punto de venta.</p>
    <div class="mt-5 overflow-x-auto"><table class="w-full"><thead><tr class="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-500"><th class="py-3">Año</th><th class="py-3">DTE</th><th class="py-3">Sucursal / POS</th><th class="py-3 text-right">Último correlativo</th><th class="py-3">Última emisión</th></tr></thead><tbody class="divide-y divide-slate-100"><?php foreach($sequences as $seq): ?><tr><td class="py-3 font-bold"><?= esc((string)$seq['year']) ?></td><td class="py-3"><span class="font-bold"><?= esc($seq['document_code']) ?></span><span class="ml-2 text-xs text-slate-500">MH <?= esc($seq['document_mh_code']) ?></span></td><td class="py-3"><p class="font-mono font-semibold"><?= esc($seq['establishment_mh_code']).esc($seq['point_of_sale_mh_code']) ?></p><p class="text-xs text-slate-500"><?= esc($seq['establishment_name']) ?> · <?= esc($seq['point_of_sale_name']) ?></p></td><td class="py-3 text-right font-mono font-bold"><?= str_pad((string)$seq['current_value'],15,'0',STR_PAD_LEFT) ?></td><td class="py-3 text-sm text-slate-600"><?= esc($seq['last_issued_at'] ?: 'Sin emisión') ?></td></tr><?php endforeach ?><?php if($sequences===[]): ?><tr><td colspan="5" class="py-8 text-center text-sm text-slate-500">Todavía no se han consumido correlativos.</td></tr><?php endif ?></tbody></table></div>
</section>

<?= $this->endSection() ?>
