<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<?php
$score=(int)$case['health_score'];
$healthClass=$score>=80?'bg-emerald-100 text-emerald-800':($score>=50?'bg-amber-100 text-amber-800':'bg-red-100 text-red-800');
$stageLabels=['commercial_acceptance'=>'Aceptación comercial','billing_definition'=>'Definición de facturación','coordination'=>'Coordinación','execution'=>'Ejecución','operational_closure'=>'Cierre operativo','billing'=>'Facturación','collection'=>'Cobro','archive'=>'Archivo'];
?>
<div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between">
    <div><p class="text-xs font-semibold uppercase tracking-[.2em] text-cyan-600">Service Case Workspace</p><h2 class="mt-2 text-3xl font-bold text-slate-950"><?= esc($case['code']) ?></h2><div class="mt-3 flex flex-wrap items-center gap-3"><span class="rounded-full px-3 py-1 text-xs font-bold <?= $healthClass ?>">Salud <?= $score ?>%</span><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700"><?= esc($stageLabels[$case['current_stage']] ?? str_replace('_',' ',$case['current_stage'])) ?></span><?php if (!empty($case['quotation_code'])): ?><a href="<?= route_to('quotations.show',$case['accepted_quotation_id']) ?>" class="font-semibold text-violet-700"><?= esc($case['quotation_code']) ?> ↗</a><?php endif ?></div></div>
    <a href="<?= route_to('service_cases.index') ?>" class="rounded-xl border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-700">Volver a expedientes</a>
</div>

<section class="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4">
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Cliente</p><p class="mt-3 text-lg font-bold text-slate-950"><?= esc($case['business_name'] ?: 'Sin cliente') ?></p><p class="mt-1 text-sm text-slate-500"><?= esc($case['trade_name'] ?: '') ?></p></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Responsable</p><p class="mt-3 text-lg font-bold text-slate-950"><?= esc($case['responsible_user_name'] ?: 'Sin asignar') ?></p></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Monto acordado</p><p class="mt-3 text-lg font-bold text-slate-950">$<?= esc(number_format((float)($case['quotation_total'] ?? 0),2)) ?></p></article>
    <article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-wide text-slate-500">Apertura</p><p class="mt-3 text-lg font-bold text-slate-950"><?= esc(date('d/m/Y H:i',strtotime($case['opened_at']))) ?></p></article>
</section>

<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_360px]">
<div class="space-y-6">
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-600">Hitos del expediente</p><h3 class="mt-2 text-xl font-bold text-slate-950">Ruta completa del servicio</h3></div><div class="mt-6 space-y-3"><?php foreach($milestones as $milestone): $done=$milestone['status']==='completed'; ?><article class="flex gap-4 rounded-xl border <?= $done?'border-emerald-200 bg-emerald-50':'border-slate-200 bg-slate-50' ?> p-4"><div class="flex h-8 w-8 shrink-0 items-center justify-center rounded-full <?= $done?'bg-emerald-500 text-white':'bg-white text-slate-400 border border-slate-300' ?>"><?= $done?'✓':esc((string)$milestone['sequence']) ?></div><div><p class="font-bold text-slate-900"><?= esc($milestone['milestone_label']) ?></p><p class="mt-1 text-xs text-slate-500"><?= $done?'Completado '.esc((string)$milestone['completed_at']):'Pendiente' ?></p><?php if(!empty($milestone['notes'])): ?><p class="mt-2 text-sm text-slate-600"><?= esc($milestone['notes']) ?></p><?php endif ?></div></article><?php endforeach ?></div></section>

<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-600">Timeline</p><h3 class="mt-2 text-xl font-bold text-slate-950">Movimientos del expediente</h3><div class="mt-6 space-y-5"><?php foreach($events as $event): ?><div class="relative border-l-2 border-slate-200 pl-5"><span class="absolute -left-[7px] top-1 h-3 w-3 rounded-full bg-cyan-500"></span><p class="font-bold text-slate-900"><?= esc($event['title']) ?></p><p class="mt-1 text-sm text-slate-600"><?= esc($event['description'] ?: '') ?></p><p class="mt-2 text-xs text-slate-400"><?= esc(date('d/m/Y H:i',strtotime($event['occurred_at']))) ?></p></div><?php endforeach ?><?php if($events===[]): ?><p class="text-sm text-slate-500">Todavía no hay movimientos adicionales.</p><?php endif ?></div></section>
</div>

<aside class="space-y-6 xl:sticky xl:top-6 xl:self-start">
<section class="rounded-2xl bg-slate-950 p-6 text-white shadow-xl"><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-400">Próxima acción</p><h3 class="mt-3 text-xl font-bold"><?= esc($nextAction['label']) ?></h3><?php if($nextAction['blocked']): ?><p class="mt-3 text-sm leading-6 text-red-200">Esta acción está bloqueada por excepciones abiertas.</p><?php else: ?><p class="mt-3 text-sm leading-6 text-slate-300">El expediente está listo para continuar cuando el módulo responsable complete este hito.</p><?php endif ?></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><p class="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Excepciones abiertas</p><span class="rounded-full bg-red-100 px-2.5 py-1 text-xs font-bold text-red-700"><?= count($exceptions) ?></span></div><div class="mt-5 space-y-3"><?php foreach($exceptions as $exception): ?><article class="rounded-xl border border-red-200 bg-red-50 p-4"><p class="font-bold text-red-900"><?= esc($exception['title']) ?></p><p class="mt-1 text-sm text-red-700"><?= esc($exception['description'] ?: '') ?></p><p class="mt-2 text-xs font-semibold uppercase text-red-500"><?= esc($exception['severity']) ?></p></article><?php endforeach ?><?php if($exceptions===[]): ?><p class="text-sm text-slate-500">No hay excepciones abiertas.</p><?php endif ?></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-[.18em] text-slate-500">Estados financieros</p><dl class="mt-5 space-y-4 text-sm"><div class="flex justify-between gap-4"><dt class="text-slate-500">Operación</dt><dd class="font-semibold text-slate-900"><?= esc(str_replace('_',' ',$case['operational_status'])) ?></dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Facturación</dt><dd class="font-semibold text-slate-900"><?= esc(str_replace('_',' ',$case['billing_status'])) ?></dd></div><div class="flex justify-between gap-4"><dt class="text-slate-500">Cobro</dt><dd class="font-semibold text-slate-900"><?= esc(str_replace('_',' ',$case['collection_status'])) ?></dd></div></dl></section>
</aside>
</div>
<?= $this->endSection() ?>
