<?= $this->extend('layouts/admin') ?>
<?= $this->section('content') ?>
<?php $isPrepared=$order['status']==='prepared'; ?>
<?php if(session('success')): ?><div class="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-emerald-800"><?= esc(session('success')) ?></div><?php endif ?>
<div class="mb-6 flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><div><p class="text-xs font-semibold uppercase tracking-[.2em] text-cyan-600">Work Order Workspace</p><h2 class="mt-2 text-3xl font-bold text-slate-950"><?= esc($order['code']) ?></h2><div class="mt-3 flex flex-wrap gap-3 text-sm"><a href="<?= route_to('service_cases.show',$order['service_case_id']) ?>" class="font-bold text-violet-700"><?= esc($order['service_case_code']) ?> ↗</a><a href="<?= route_to('coordination.show',$order['coordination_plan_id']) ?>" class="font-bold text-cyan-700"><?= esc($order['coordination_code']) ?> ↗</a><span class="rounded-full bg-slate-200 px-3 py-1 text-xs font-bold text-slate-700"><?= esc(ucfirst($order['status'])) ?></span></div></div><a href="<?= route_to('work_orders.index') ?>" class="rounded-xl border border-slate-300 bg-white px-5 py-3 font-semibold text-slate-700">Volver a órdenes</a></div>
<section class="mb-6 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase text-slate-500">Cliente</p><p class="mt-3 font-bold"><?= esc($order['business_name']??'—') ?></p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase text-slate-500">Programación</p><p class="mt-3 font-bold"><?= esc($order['scheduled_start_at']?date('d/m/Y H:i',strtotime($order['scheduled_start_at'])):'—') ?></p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase text-slate-500">Ubicación</p><p class="mt-3 font-bold"><?= esc($order['location']??'—') ?></p></article><article class="rounded-2xl border border-slate-200 bg-white p-5"><p class="text-xs uppercase text-slate-500">Prioridad</p><p class="mt-3 font-bold"><?= esc(ucfirst($order['priority'])) ?></p></article></section>
<div class="grid gap-6 xl:grid-cols-[minmax(0,1fr)_380px]"><div class="space-y-6">
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-600">Misión</p><h3 class="mt-2 text-xl font-bold"><?= esc($order['subject']??'Orden de Trabajo') ?></h3><div class="mt-5 grid gap-4 md:grid-cols-2"><div><p class="text-xs uppercase text-slate-500">Inicio</p><p class="mt-2 font-semibold"><?= esc($order['scheduled_start_at']?date('d/m/Y H:i',strtotime($order['scheduled_start_at'])):'—') ?></p></div><div><p class="text-xs uppercase text-slate-500">Fin estimado</p><p class="mt-2 font-semibold"><?= esc($order['estimated_end_at']?date('d/m/Y H:i',strtotime($order['estimated_end_at'])):'—') ?></p></div></div><?php if(!empty($order['scope_snapshot'])): ?><div class="mt-5 border-t border-slate-100 pt-5"><p class="text-xs uppercase text-slate-500">Alcance operativo</p><p class="mt-3 whitespace-pre-line text-sm leading-6 text-slate-700"><?= esc($order['scope_snapshot']) ?></p></div><?php endif ?></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-600">Maquinaria asignada</p><h3 class="mt-2 text-xl font-bold">Recursos físicos</h3></div><div class="mt-5 grid gap-3 md:grid-cols-2"><?php foreach($equipment as $item): ?><article class="rounded-xl border border-slate-200 bg-slate-50 p-4"><p class="font-bold"><?= esc($item['equipment_code_snapshot']) ?> · <?= esc($item['equipment_name_snapshot']) ?></p><p class="mt-1 text-xs text-slate-500"><?= esc(ucfirst($item['assignment_status'])) ?></p></article><?php endforeach ?></div></section>
<section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-600">Equipo operativo</p><h3 class="mt-2 text-xl font-bold">Personal de la misión</h3></div><div class="mt-5 grid gap-3 md:grid-cols-2"><?php foreach($team as $member): ?><article class="rounded-xl border <?= $member['allocation_type']==='mission_leader'?'border-violet-200 bg-violet-50':'border-slate-200 bg-slate-50' ?> p-4"><p class="font-bold"><?= esc($member['employee_name_snapshot']) ?></p><p class="mt-1 text-sm text-slate-600"><?= esc($member['role_name_snapshot']??'Recurso operativo') ?></p><p class="mt-1 text-xs text-slate-500"><?= esc($member['employee_code_snapshot']) ?> · <?= esc(ucfirst($member['assignment_status'])) ?></p></article><?php endforeach ?></div></section>
</div><aside class="space-y-6 xl:sticky xl:top-6 xl:self-start"><section class="rounded-2xl bg-slate-950 p-6 text-white shadow-xl"><p class="text-xs font-semibold uppercase tracking-[.18em] text-cyan-400">Próxima acción</p><h3 class="mt-3 text-xl font-bold"><?= $isPrepared?'Emitir Orden de Trabajo':'Ejecución operativa' ?></h3><p class="mt-4 text-sm leading-6 text-slate-300"><?= $isPrepared?'La OT fue generada desde una coordinación aprobada. El siguiente incremento controlará su emisión formal y entrega al responsable de misión.':'La Orden de Trabajo avanzará por estados controlados de ejecución.' ?></p></section><section class="rounded-2xl border border-slate-200 bg-white p-6"><p class="text-xs uppercase tracking-wide text-slate-500">Trazabilidad</p><div class="mt-4 space-y-3 text-sm"><p><span class="text-slate-500">Expediente:</span> <strong><?= esc($order['service_case_code']) ?></strong></p><p><span class="text-slate-500">Coordinación:</span> <strong><?= esc($order['coordination_code']) ?></strong></p><p><span class="text-slate-500">Creada:</span> <strong><?= esc($order['entry_date']?date('d/m/Y H:i',strtotime($order['entry_date'])):'—') ?></strong></p></div></section></aside></div>
<?= $this->endSection() ?>
